version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=8080
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

    depends_on:
      - redis

  redis:
    image: redis:5
